In [ ]:
import numpy as np
import torch

In [ ]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 1.49  1.02  3.07  2.32  0.3 ]
 [-1.15  1.94  1.97  3.23 -0.61]
 [ 1.21  0.38  1.13  0.71 -0.65]]
 
[[-1.04  0.15 -1.68  1.47]
 [-2.08 -0.4  -1.3   1.35]
 [-0.44 -0.46  1.02 -0.76]
 [ 2.04  2.13  0.4  -1.33]
 [ 2.43  2.01 -0.46 -0.45]
 [ 0.97  1.67  0.36 -1.11]
 [ 1.63  0.8   1.51 -1.75]]


# PyTorch


In [ ]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.3400,  1.0100,  2.2600,  0.5100,  2.6200,  5.0600,  7.3500],
        [-0.5600,  0.4300, -0.1800, -0.4700,  0.9500,  2.2700,  3.7400],
        [-1.3400, -1.2900, -2.4300, -1.6800, -1.2800, -2.6200, -2.5900]],
       dtype=torch.float64)
 
tensor([[ 0.3400,  1.0100,  2.2600,  0.5100,  2.6200,  5.0600,  7.3500],
        [-0.5600,  0.4300, -0.1800, -0.4700,  0.9500,  2.2700,  3.7400],
        [-1.3400, -1.2900, -2.4300, -1.6800, -1.2800, -2.6200, -2.5900]])


/tmp/ipython-input-4136805860.py:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round( A@C1  ,2)), print(' ')
